name: Test Scenario
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: setup config
        run: mv tests/config/configExample.ts tests/config/config.ts
      - name: Setup test Env
        run: |
          yarn install
          docker-compose up -d
          yarn build
      - name: run
        shell: bash
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: docker compose run k6 run --compatibility-mode=base - < ./dist/httpGet.js
